pipeline:
  name: k8s
  identifier: k8s
  projectIdentifier: jagruti_playground_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: k8s
        identifier: k8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8sservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: minikubeenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: minkubeinfra
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_1
                  identifier: K8sRollingDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: true
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        delegateSelectors:
          - helm-delegate
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: PipelineRollback
