pipeline:
  name: my-pipeline
  identifier: mypipeline
  projectIdentifier: jagruti_playground_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnector
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Owasp
                      name: Owasp_1
                      identifier: Owasp_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: OsvScanner
                      name: OsvScanner_1
                      identifier: OsvScanner_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
              - step:
                  type: Run
                  name: my-java-application
                  identifier: myjavaapplication
                  spec:
                    shell: Sh
                    command: |-
                      echo "building java application"
                      mvn -B package --file zenzbg-template/greetings/pom.xml
              - step:
                  type: Run
                  name: upload artifact to jfrog
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      echo "⬇️ Installing JFrog CLI..."
                      curl -fL https://getcli.jfrog.io | sh
                      chmod +x jfrog
                      mv jfrog /usr/local/bin/jfrog
                      export JFROG_CLI_OFFER_CONFIG=false

                      echo "🚀 Uploading artifact to JFrog..."
                      jfrog rt u \
                        "zenzbg-template/greetings/target/greetings-1.0.0.jar" \
                        "harness-generic-local/java-apps/" \
                        --url="https://rushiops.jfrog.io/artifactory" \
                        --access-token <+secrets.getValue("j-token")> \
                        --build-name <+pipeline.identifier> \
                        --build-number <+pipeline.sequenceId> \
                        --target-props "project=greetings;env=dev"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: rushiops/demo-harness
                    tags:
                      - latest
                    dockerfile: zenzbg-template/greetings/Dockerfile
                    context: zenzbg-template/greetings
          sharedPaths:
            - /var/run
        description: ""
        when:
          pipelineStatus: Success
