pipeline:
  name: my-pipeline
  identifier: mypipeline
  projectIdentifier: jagruti_playground_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnector
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: my-java-application
                  identifier: myjavaapplication
                  spec:
                    shell: Sh
                    command: |-
                      echo "building java application"
                      mvn -B package --file zenzbg-template/greetings/pom.xml
              - parallel:
                  - step:
                      type: OsvScanner
                      name: OsvScanner_1
                      identifier: OsvScanner_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: Owasp
                      name: Owasp_1
                      identifier: Owasp_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: rushiops/demo-harness
                    tags:
                      - latest
                    dockerfile: zenzbg-template/greetings/Dockerfile
                    context: zenzbg-template/greetings
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      echo "$key" > key3.pem
                      chmod 400 key3.pem
                      ssh -i key3.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@54.204.105.70
                      whoami
                      curl ifconfig.io
                      docker -v
                      cat /etc/os-release
                      pwd
                      echo "Pulling image "
                      sudo docker pull rushiops/demo-harness:latest
                      sudo docker run -d --name demo-harness -p 8080:8080 rushiops/demo-harness:latest
                    envVariables:
                      key: <+secrets.getValue("azure-key-file")>
          sharedPaths:
            - /var/run
        description: ""
        when:
          pipelineStatus: Success
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: javaappservice
          environment:
            environmentRef: envjavaapp
            deployToAll: false
            infrastructureDefinitions:
              - identifier: azurevmtypeinfra
          execution:
            steps:
              - step:
                  type: ShellScriptProvision
                  name: ShellScriptProvision_1
                  identifier: ShellScriptProvision_1
                  spec:
                    source:
                      type: Inline
                      spec:
                        script: |
                          #!/bin/bash


                          echo "$key" > key3.pem
                          chmod 400 key3.pem
                          ssh -i key3.pem -o StrictHostKeyChecking=no ubuntu@54.204.105.70 <<EOF
                          echo "Connected to EC2."
                          curl ifconfig.io
                          whoami
                          cat /etc/os-release
                          pwd
                          echo "Pulling image "
                          sudo docker pull rushiops/demo-harness:latest
                          sudo docker stop demo-harness 
                          sudo docker rm demo-harness
                          sudo docker run -d --name demo-harness -p 8080:8080 rushiops/demo-harness:latest
                          EOF 
                    environmentVariables:
                      - name: key
                        type: String
                        value: <+secrets.getValue("azure-key-file")>
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: ManualIntervention
                spec:
                  onTimeout:
                    action:
                      type: StageRollback
                  timeout: 1d 4h 30m 15s
