pipeline:
  name: my-pipeline
  identifier: mypipeline
  projectIdentifier: jagruti_playground_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnector
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: my-java-application
                  identifier: myjavaapplication
                  spec:
                    shell: Sh
                    command: |-
                      echo "building java application"
                      mvn -B package --file zenzbg-template/greetings/pom.xml
              - parallel:
                  - step:
                      type: OsvScanner
                      name: OsvScanner_1
                      identifier: OsvScanner_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: Owasp
                      name: Owasp_1
                      identifier: Owasp_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: rushiops/demo-harness
                    tags:
                      - latest
                    dockerfile: zenzbg-template/greetings/Dockerfile
                    context: zenzbg-template/greetings
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      echo "$key" > key2.pem
                      chmod 400 key2.pem
                      ssh -i key2.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vm@20.244.32.79
                      whoami
                      curl ifconfig.io
                      docker -v
                      cat /etc/os-release
                      pwd
                      echo "Pulling image "
                      sudo docker pull 46990406/demo-harness:latest
                      sudo docker run -d --name demo-harness -p 8080:8080 46990406/demo-harness:latest
                    envVariables:
                      key: <+secrets.getValue("azure-key-file")>
          sharedPaths:
            - /var/run
        description: ""
    - stage:
        name: deployment
        identifier: deployment
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "$key" > key2.pem
                          chmod 400 key2.pem
                          ssh -i key2.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vm@20.244.32.79
                          whoami
                          curl ifconfig.io
                          docker -v
                          cat /etc/os-release
                          pwd
                          echo "Pulling image "
                          sudo docker pull 46990406/demo-harness:latest
                          sudo docker run -d --name demo-harness -p 8080:8080 46990406/demo-harness:latest
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
