pipeline:
  name: new-ci
  identifier: newci
  projectIdentifier: jagruti_playground_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnector
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Java App
                  identifier: build_java
                  spec:
                    shell: Sh
                    command: |-
                      echo "🔨 Building Maven project..."
                      cd zenzbg-template/greetings
                      mvn clean install
              - step:
                  type: Plugin
                  name: Upload to JFrog
                  identifier: upload_to_jfrog
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/artifactory
                    settings:
                      access_token: <+secrets.getValue("jfrog_access_token")>
                      url: https://rushiops.jfrog.io/artifactory
                      source: zenzbg-template/greetings/target/greetings-1.0.0.jar
                      target: harness-generic-local/java-apps/greetings-1.0.0.jar
                      build_name: <+pipeline.identifier>
                      build_number: <+pipeline.sequenceId>
                      publish_build_info: true
                      targetProps: project=greetings;env=dev
