apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-ms  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings-ms 
  template:
    metadata:
      labels:
        app: greetings-ms
    spec:
      containers:
      - name: greetings-ms
        image: zenzdevelopmentregistry.azurecr.io/zenzbg-template:{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: TITLE
          value: "AKS Ingress Demo"
---
kind: Service 
apiVersion: v1 
metadata:
  name: greetings-ms 
spec:
  type: LoadBalancer
  selector:
    app: greetings-ms 
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080

