apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      containers:
        - name: java-app
          image: rushiops/demo-harness:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java-service
spec:
  selector:
    app: demo-java
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
