trigger:
- none
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     vmImage: ubuntu-latest
    
      
    steps:
    - task: Maven@4
      displayName: 'Maven greetings/pom.xml'
      inputs:
        mavenPomFile: greetings/pom.xml
        goals: 'clean install package'
    
  
    - task: Docker@2
      inputs:
        containerRegistry: 'ZenzDevelopmentRegistry-2138'
        repository: 'zenzbg-template'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(Build.BuildNumber)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          #Replace the placeholder {{TAG}} with the build number
          sed -i 's#{{TAG}}#$(Build.BuildNumber)#' greetings/greetings-aks.yaml
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/greetings/greetings-aks.yaml
        artifact: 'drop'
        publishLocation: 'pipeline'
- stage: Deploy
  dependsOn: Build
  
  jobs:
    - deployment: production
      pool:
        vmImage: ubuntu-latest
      environment: dev
      strategy:
        runOnce:
          
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  targetPath: '$(Pipeline.Workspace)'
              - task: KubernetesManifest@1
                inputs:
                  action: 'deploy'
                  connectionType: 'kubernetesServiceConnection'
                  kubernetesServiceConnection: 'ZenzDevCluster-zenzbg-template-ns'
                  namespace: 'zenzbg-template-ns'
                  manifests: $(Pipeline.Workspace)/drop/greetings-aks.yaml

